csharp4-lesson14/Models/blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using csharp4_lesson14.Models;
namespace csharp4_lesson14.Models
{
    public class blog
    {
        [Key]
        public int blogid { get; set; }
        [Display(Name = "Name")]
        public int userid { get; set; }
        public string title { get; set; }
        public string username { get; set; }
        [Display(Name = "Date")]
        public virtual List<posts> posts { get; set; }
    }
}

csharp4-lesson14/Controllers/blogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using csharp4_lesson14.Models;
using System.Data;

namespace csharp4_lesson14.Controllers
{
    public class blogController : Controller
    {
        blogcontext b = new blogcontext();
        //
        // GET: /blog/

        public ActionResult Index()
        {
            if (b.blogs != null)
            {
                return View("bloglist");
            }
            return View();
        }

        public ActionResult bloglist()
        {
            return View(b.blogs.ToList());
        }

        public ActionResult postlist()
        {
            return View(b.posts.ToList());
        }

        public ActionResult commentlist()
        {
            return View(b.comments.ToList());
        }

        public ActionResult viewblog(int? id)
        {
            return View(b.blogs.Find(id));
        }


        public ActionResult addpost()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult addpost(posts posttocreate)
        {
            if (ModelState.IsValid)
            {
                b.posts.Add(posttocreate);
                b.SaveChanges();
                return RedirectToAction("bloglist");
            }
            return View(posttocreate);
        }

        public ActionResult editpost(int? id)
        {
            posts item = b.posts.Find(id);
            if (item == null)
            {
                return View();
            }
            return View(item);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult editpost(posts posttoedit)
        {
            if (!ModelState.IsValid)
            {
                return View(posttoedit);
            }
            b.Entry(posttoedit).State = EntityState.Modified;
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        public ActionResult deletepost(int? id)
        {
            posts item = b.posts.Find(id);
            if (item == null)
            {
                return View();
            }
            b.posts.Remove(item);
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("deletepost")]
        public ActionResult deletepostcofirmed(int id)
        {
            posts item = b.posts.Find(id);
            b.posts.Remove(item);
            b.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult addblog()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("addblog")]
        public ActionResult addblog([Bind(Exclude = "id")] blog blogtocreate)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            b.blogs.Add(blogtocreate);
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        public ActionResult removeblog(int? id)
        {
            blog item = b.blogs.Find(id);
            if (item == null)
            {
                return View("Index");
            }
            b.blogs.Remove(item);
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("removeblog")]
        public ActionResult removeblogcofirmed(int id)
        {
            blog item = b.blogs.Find(id);
            b.blogs.Remove(item);
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        public ActionResult addcomments()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("addcomments")]
        public ActionResult addcomments([Bind(Exclude = "id")] comments commenttocreate)
        {            
            if (!ModelState.IsValid)
            {
                return View();
            }
            b.comments.Add(commenttocreate);
            b.SaveChanges();
            return RedirectToAction("bloglist");   
        }

        public ActionResult removecomments(int? id)
        {
            comments item = b.comments.Find(id);
            b.comments.Remove(item);
            b.SaveChanges();
            return RedirectToAction("bloglist");
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("removecomments")]
        public ActionResult removecommentscofirmed(int? id)
        {
            comments item = b.comments.Find(id);
            if (item == null)
            {
                return View("Index");
            }
            b.comments.Remove(item);
            b.SaveChanges();
            return RedirectToAction("viewblog");
        }

        public ActionResult getpostsbyblogid(int id)
        {
            var p = b.posts.Where(a => a.fkblog == id);
            return View(p.ToList());
        }

        public ActionResult viewpost(int id)
        {
            return View(b.posts.Find(id));
        }

    }
}

csharp4-lesson14/Views/blog/Index.cshtml
@model  IEnumerable<csharp4_lesson14.Models.blog>
    @{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add Blog", "addblog", "blog")
@Html.ActionLink("Blog List", "bloglist", "blog")

csharp4-lesson14/Views/blog/addblog.cshtml
@model csharp4_lesson14.Models.blog
    @{
    ViewBag.Title = "Add Blog";
}


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Blog</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>
        <p>
            <input type="submit" value="Add" />
        </p>
    </fieldset>
}

csharp4-lesson14/Views/blog/addcomments.cshtml
@model csharp4_lesson14.Models.comments
@{
    ViewBag.Title = "Add Comments";
}

<h2>addcomment</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comments</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content)
            @Html.ValidationMessageFor(model => model.content)
        </div>
        <p>
            <input type="submit" value="Add" />
        </p>
    </fieldset>
}

csharp4-lesson14/Views/blog/addpost.cshtml
@model csharp4_lesson14.Models.posts
    @{
    ViewBag.Title = "Add Post";
}

<h2>addblog</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Post</legend>
          <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content)
            @Html.ValidationMessageFor(model => model.content)
        </div>
        <p>
            <input type="submit" value="Add" />
        </p>
    </fieldset>
}

csharp4-lesson14/Views/blog/bloglist.cshtml
@model  IEnumerable<csharp4_lesson14.Models.blog>
    @{
    ViewBag.Title = "Blog List";
}

<h2>Blog List</h2>
@if (Request.IsAuthenticated)
{
    @Html.ActionLink("Add Blog", "addblog", "blog", new { username = User.Identity.Name },null);
}
<table>
<tr>
    <td>Title</td>
    <td>Count</td>
    <td>Author</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td>@x.title</td>
        <td>@x.posts.Count</td>
        <td>@x.username</td>
        <td>@Html.ActionLink("View", "viewblog", new { id = x.blogid })</td>
        @if (Request.IsAuthenticated && User.Identity.Name==x.username)
        {
            <td>@Html.ActionLink("Delete", "removeblog", new { id = x.blogid })</td>
            
        }
    </tr>
}
</table>

csharp4-lesson14/Views/blog/commentlist.cshtml
@model  IEnumerable<csharp4_lesson14.Models.comments>
    @{
    ViewBag.Title = "Comments List";
}

<h2>Comments List</h2>
@Html.ActionLink("Add Blog", "addblog", "blog");
<table>
@foreach (var x in Model)
{
    <tr>
        <td>@x.id</td>
        <td>@x.content</td>
    </tr>
}
</table>

csharp4-lesson14/Views/blog/deleteblog.cshtml
@{
    ViewBag.Title = "deleteblog";
}

<h2>deleteblog</h2>

csharp4-lesson14/Views/blog/deletepost.cshtml
@{
    ViewBag.Title = "deletepost";
}

<h2>deletepost</h2>

csharp4-lesson14/Views/blog/editblog.cshtml
@model csharp4_lesson14.Models.blog
    @{
    ViewBag.Title = "Edit Blog";
}

<h2>editblog</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit Blog</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>
        <p>
            <input type="submit" value="Edit" />
        </p>
    </fieldset>
}

csharp4-lesson14/Views/blog/getpostsbyblogid.cshtml
@model IEnumerable<csharp4_lesson14.Models.posts>
@{
    ViewBag.Title = "Posts";
}

<h2>Posts</h2>

<table>
@foreach (var x in Model)
{    
    <tr>
        @if (Request.IsAuthenticated && User.Identity.Name==x.blog.username)
        {
            <td>@Html.ActionLink("Edit", "editpost", new { id = x.id })</td>
            <td>@Html.ActionLink("Delete", "deletepost", new { id = x.id })</td>
        }
        <td>@Html.ActionLink("View", "viewpost", new { id = x.id })</td>
        <td>@Html.DisplayFor(model => x.content)</td>
        <td>@Html.DisplayFor(model => x.comments)</td>
    </tr>
}
</table>

csharp4-lesson14/Views/blog/removeblog.cshtml
@{
    ViewBag.Title = "removeblog";
}

<h2>removeblog</h2>

csharp4-lesson14/Views/blog/removecomments.cshtml
@{
    ViewBag.Title = "removecomments";
}

<h2>removecomments</h2>

csharp4-lesson14/Views/blog/viewblog.cshtml
@model csharp4_lesson14.Models.blog
@{
    ViewBag.Title = "Viewing Blog List";
}


<h2>@Html.DisplayFor(x => x.title)</h2>
@if (Request.IsAuthenticated)
{
    @Html.ActionLink("Add Post", "addpost", new { fkblog = Model.blogid })
}
@foreach (var y in Model.posts)
{
    <h3>@y.title</h3>
    <p>@y.blog.username</p>
    <p>@y.content</p>  
    if (Request.IsAuthenticated && User.Identity.Name == y.blog.username)
    {
        <table>
            <tr>
                <td>@Html.ActionLink("Edit", "editpost", new { id = y.id , fkblog = Model.blogid})</td>
                <td>@Html.ActionLink("Delete", "deletepost", new { id = y.id, fkblog = Model.blogid })</td>
            </tr>
        </table>
    }  
    <p>@Html.ActionLink("Add Comment", "addcomments", new { fkpost = y.id })</p>        
    foreach (var z in y.comments)
    {
        <p>@z.content</p>
        if (Request.IsAuthenticated && User.Identity.Name == y.blog.username)
        {
            <p>@Html.ActionLink("Remove Comment", "removecomments", new { id = z.id })</p>
        }
    }
}

csharp4-lesson14/Views/blog/viewpost.cshtml
@model csharp4_lesson14.Models.posts
@{
    ViewBag.Title = "viewpost";
}

<h2>View Post</h2>
<div>
@Model.content
</div>
<div>
<ul>
@foreach (var y in Model.comments)
{
    <li>@y.content</li>
}
</ul>
</div>
@Html.ActionLink("Add Comment", "addcomments", new { fkpost = Model.id })